# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# Production builds require fast refresh disabled
production = ENV['PRODUCTION'] == '1'

target 'FieldSync' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => !production ? FlipperConfiguration.enabled : FlipperConfiguration.disabled,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # React Native Maps
  pod 'react-native-google-maps', :path => '../node_modules/react-native-maps'
  
  # Location services
  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
  
  # Camera and vision
  pod 'VisionCamera', :path => '../node_modules/react-native-vision-camera'
  
  # Permissions
  pod 'Permission-Camera', :path => '../node_modules/react-native-permissions/ios/Camera'
  pod 'Permission-LocationAlways', :path => '../node_modules/react-native-permissions/ios/LocationAlways'
  pod 'Permission-LocationWhenInUse', :path => '../node_modules/react-native-permissions/ios/LocationWhenInUse'
  pod 'Permission-Microphone', :path => '../node_modules/react-native-permissions/ios/Microphone'
  pod 'Permission-PhotoLibrary', :path => '../node_modules/react-native-permissions/ios/PhotoLibrary'

  target 'FieldSyncTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
    
    # Fix for Xcode 15+ build issues
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = min_ios_version_supported
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end